### ISSUE TITLE
Is traditional algorithm suitable on an asynchronous featured language?

### ISSUE THREAD

**Issue by LukeXuan** [arrowrowe/algorithms-node#1]

**Comment by arrowrowe** [comment]
I choose Node just because ES6 seems cool, with arrow functions and other stuff, and I am more or less familiar with JavaScript and its test suites (i.e. Mocha, Chai, and Istanbul), considering Haskell or Ruby. I may try Python in another repo some day.

And in fact my code here is NOT asynchronous, though it's kind of a waste if you strongly believe it a basic idea to code asynchronously in Node.

Anyway, may code speak for itself, and thanks a lot for advising! Looking forward to any reply.

**Comment by arrowrowe** [comment]
Close due to TLE. Feel free to reopen it any time!

**Comment by gaocegege** [comment]
👍加油！别弃坑！

**Comment by arrowrowe** [comment]
re @gaocegege: same to u :smiley:

**Comment by arrowrowe** [comment]
Close due to TLE. (Forgot to close last time...)

Since all problems from [sagivo/algorithms](https://github.com/sagivo/algorithms) have been included, this repo may stay silent for a while.

:smile:
